### ISSUE TITLE
Unable to start after updates

### ISSUE THREAD

**Issue by SanderGit** [jlesage/docker-jdownloader-2#128]
on Synology in Docker

```
[init        ] container is starting...
[cont-env    ] loading container environment variables...
[cont-env    ] APP_NAME: loading...
[cont-env    ] DISPLAY: executing...
[cont-env    ] DISPLAY: terminated successfully.
[cont-env    ] DISPLAY: loading...
[cont-env    ] DOCKER_IMAGE_PLATFORM: loading...
[cont-env    ] DOCKER_IMAGE_VERSION: loading...
[cont-env    ] GTK_THEME: executing...
[cont-env    ] GTK_THEME: /etc/cont-env.d/GTK_THEME: line 6: is-bool-val-true: not found
[cont-env    ] GTK_THEME: terminated successfully.
[cont-env    ] GTK_THEME: loading...
[cont-env    ] HOME: loading...
[cont-env    ] INSTALL_PACKAGES_INTERNAL: executing...
[cont-env    ] INSTALL_PACKAGES_INTERNAL: terminated successfully.
[cont-env    ] INSTALL_PACKAGES_INTERNAL: loading...
[cont-env    ] QT_STYLE_OVERRIDE: executing...
[cont-env    ] QT_STYLE_OVERRIDE: /etc/cont-env.d/QT_STYLE_OVERRIDE: line 6: is-bool-val-true: not found
[cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.
[cont-env    ] QT_STYLE_OVERRIDE: loading...
[cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...
[cont-env    ] XDG_CACHE_HOME: loading...
[cont-env    ] XDG_CONFIG_HOME: loading...
[cont-env    ] XDG_DATA_HOME: loading...
[cont-env    ] XDG_RUNTIME_DIR: loading...
[cont-env    ] container environment variables initialized.
[cont-secrets] loading container secrets...
[cont-secrets] container secrets loaded.
[cont-init   ] executing container initialization scripts...
[cont-init   ] 10-certs.sh: executing...
[cont-init   ] 10-certs.sh: /etc/cont-init.d/10-certs.sh: line 7: is-bool-val-true: not found
[cont-init   ] 10-certs.sh: terminated successfully.
[cont-init   ] 10-check-app-niceness.sh: executing...
[cont-init   ] 10-check-app-niceness.sh: terminated successfully.
[cont-init   ] 10-cjk-font.sh: executing...
[cont-init   ] 10-cjk-font.sh: /etc/cont-init.d/10-cjk-font.sh: line 6: is-bool-val-true: not found
[cont-init   ] 10-cjk-font.sh: terminated successfully.
[cont-init   ] 10-clean-logmonitor-states.sh: executing...
[cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
[cont-init   ] 10-clean-tmp-dir.sh: executing...
[cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
[cont-init   ] 10-fontconfig-cache-dir.sh: executing...
[cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
[cont-init   ] 10-init-users.sh: executing...
[cont-init   ] 10-init-users.sh: /etc/cont-init.d/10-init-users.sh: line 86: sed-patch: not found
[cont-init   ] 10-init-users.sh: terminated with error 127.

```

**Comment by jlesage** [comment]
Can you provide the output of `docker inspect <container name>` ?

**Comment by RieGo** [comment]
I've got the same problem since last update.

my inspect:
`{
    "AppArmorProfile": "docker-default",
    "Args": [],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "/init"
        ],
        "DDSM": false,
        "Domainname": "",
        "Entrypoint": null,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "ENV=/root/.docker_rc",
            "USER_ID=1037",
            "GROUP_ID=100",
            "SUP_GROUP_IDS=",
            "UMASK=0022",
            "LANG=en_US.UTF-8",
            "TZ=Etc/UTC",
            "KEEP_APP_RUNNING=0",
            "APP_NICENESS=0",
            "INSTALL_PACKAGES=",
            "CONTAINER_DEBUG=0",
            "DISPLAY_WIDTH=1680",
            "DISPLAY_HEIGHT=960",
            "DARK_MODE=0",
            "SECURE_CONNECTION=0",
            "SECURE_CONNECTION_VNC_METHOD=SSL",
            "SECURE_CONNECTION_CERTS_CHECK_INTERVAL=60",
            "WEB_LISTENING_PORT=5800",
            "VNC_LISTENING_PORT=5900",
            "VNC_PASSWORD=",
            "ENABLE_CJK_FONT=0",
            "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
            "S6_SERVICE_DEPS=1",
            "APP_NAME=JDownloader 2",
            "APP_USER=app",
            "XDG_DATA_HOME=/config/xdg/data",
            "XDG_CONFIG_HOME=/config/xdg/config",
            "XDG_CACHE_HOME=/config/xdg/cache",
            "XDG_RUNTIME_DIR=/tmp/run/user/app",
            "DISPLAY=:0",
            "S6_KILL_GRACETIME=10000"
        ],
        "ExposedPorts": {
            "3129/tcp": {},
            "5800/tcp": {},
            "5900/tcp": {}
        },
        "Hostname": "jdownloader-2",
        "Image": "jlesage/jdownloader-2:latest",
        "Labels": {
            "org.label-schema.description": "Docker container for JDownloader 2",
            "org.label-schema.name": "jdownloader-2",
            "org.label-schema.schema-version": "1.0",
            "org.label-schema.vcs-url": "https://github.com/jlesage/docker-jdownloader-2",
            "org.label-schema.version": "1.7.2",
            "org.opencontainers.image.created": "2022-08-18T15:58:50Z",
            "org.opencontainers.image.revision": "255579be3cd8bebe461362d6e67484221a8a67c0",
            "org.opencontainers.image.source": "https://github.com/jlesage/docker-jdownloader-2.git",
            "org.opencontainers.image.url": "https://github.com/jlesage/docker-jdownloader-2"
        },
        "OnBuild": null,
        "OpenStdin": true,
        "StdinOnce": false,
        "Tty": true,
        "User": "",
        "Volumes": {
            "/config": {},
            "/output": {}
        },
        "WorkingDir": "/tmp"
    },
    "Created": "2022-12-05T16:45:27.03246784Z",
    "Driver": "btrfs",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": null,
        "Name": "btrfs"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "/volume1/docker/jdconfig:/config",
            "/volume1/J/Download:/output"
        ],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "CapAdd": null,
        "CapDrop": null,
        "Cgroup": "",
        "CgroupParent": "",
        "CgroupnsMode": "host",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 50,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": null,
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "ENV=/root/.docker_rc",
            "USER_ID=1037",
            "GROUP_ID=100",
            "SUP_GROUP_IDS=",
            "UMASK=0022",
            "LANG=en_US.UTF-8",
            "TZ=Etc/UTC",
            "KEEP_APP_RUNNING=0",
            "APP_NICENESS=0",
            "INSTALL_PACKAGES=",
            "CONTAINER_DEBUG=0",
            "DISPLAY_WIDTH=1680",
            "DISPLAY_HEIGHT=960",
            "DARK_MODE=0",
            "SECURE_CONNECTION=0",
            "SECURE_CONNECTION_VNC_METHOD=SSL",
            "SECURE_CONNECTION_CERTS_CHECK_INTERVAL=60",
            "WEB_LISTENING_PORT=5800",
            "VNC_LISTENING_PORT=5900",
            "VNC_PASSWORD=",
            "ENABLE_CJK_FONT=0",
            "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
            "S6_SERVICE_DEPS=1",
            "APP_NAME=JDownloader 2",
            "APP_USER=app",
            "XDG_DATA_HOME=/config/xdg/data",
            "XDG_CONFIG_HOME=/config/xdg/config",
            "XDG_CACHE_HOME=/config/xdg/cache",
            "XDG_RUNTIME_DIR=/tmp/run/user/app",
            "DISPLAY=:0",
            "S6_KILL_GRACETIME=10000"
        ],
        "ExtraHosts": null,
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "IpcMode": "private",
        "Isolation": "",
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "Links": null,
        "LogConfig": {
            "Config": {},
            "Type": "db"
        },
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "Memory": 2010120192,
        "MemoryReservation": 0,
        "MemorySwap": 4020240384,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "bridge",
        "OomKillDisable": false,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {
            "3129/tcp": [
                {
                    "HostIp": "",
                    "HostPort": ""
                }
            ],
            "5800/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "5800"
                }
            ],
            "5900/tcp": [
                {
                    "HostIp": "",
                    "HostPort": ""
                }
            ]
        },
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ],
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 3,
            "Name": "on-failure"
        },
        "Runtime": "runc",
        "SecurityOpt": null,
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": null
    },
    "HostnamePath": "/volume1/@docker/containers/cd1489bb000333a66f10ce05bf364af91761f760b1e8a4654ece9e0143a6e712/hostname",
    "HostsPath": "/volume1/@docker/containers/cd1489bb000333a66f10ce05bf364af91761f760b1e8a4654ece9e0143a6e712/hosts",
    "Id": "cd1489bb000333a66f10ce05bf364af91761f760b1e8a4654ece9e0143a6e712",
    "Image": "sha256:717805b0e624b5e8db46749770984db77e52f175a34903f387f6fed3915f55f0",
    "LogPath": "/volume1/@docker/containers/cd1489bb000333a66f10ce05bf364af91761f760b1e8a4654ece9e0143a6e712/log.db",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/output",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/volume1/J/Download",
            "Type": "bind"
        },
        {
            "Destination": "/config",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/volume1/docker/jdconfig",
            "Type": "bind"
        }
    ],
    "Name": "/jdownloader-2",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "Networks": {
            "bridge": {
                "Aliases": null,
                "DriverOpts": null,
                "EndpointID": "",
                "Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": null,
                "IPAddress": "",
                "IPPrefixLen": 0,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "",
                "NetworkID": "3796d81d27ccadd902e3e848de1ba35fa441bf4733c555a0aaaf069be9727233"
            }
        },
        "Ports": {},
        "SandboxID": "83aedb94d79e91b45a4a1c86502870ac1388ded2fbd211d4900177ce1db65f78",
        "SandboxKey": "/var/run/docker/netns/83aedb94d79e",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "/init",
    "Platform": "linux",
    "Portainer": {
        "ResourceControl": {
            "Id": 7,
            "ResourceId": "cd1489bb000333a66f10ce05bf364af91761f760b1e8a4654ece9e0143a6e712",
            "SubResourceIds": [],
            "Type": 1,
            "UserAccesses": [],
            "TeamAccesses": [],
            "Public": false,
            "AdministratorsOnly": true,
            "System": false
        }
    },
    "ProcessLabel": "",
    "ResolvConfPath": "/volume1/@docker/containers/cd1489bb000333a66f10ce05bf364af91761f760b1e8a4654ece9e0143a6e712/resolv.conf",
    "RestartCount": 3,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 127,
        "FinishedAt": "2022-12-05T16:45:40.305050139Z",
        "FinishedTs": 1670258740,
        "OOMKilled": false,
        "Paused": false,
        "Pid": 0,
        "Restarting": false,
        "Running": false,
        "StartedAt": "2022-12-05T16:45:40.239652012Z",
        "StartedTs": 1670258740,
        "Status": "exited"
    }
}`



Log:
`[cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.

[cont-init   ] 10-clean-tmp-dir.sh: executing...

[cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.

[cont-init   ] 10-fontconfig-cache-dir.sh: executing...

[cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.

[cont-init   ] 10-init-users.sh: executing...

[cont-init   ] 10-init-users.sh: /etc/cont-init.d/10-init-users.sh: line 86: sed-patch: not found

[cont-init   ] 10-init-users.sh: terminated with error 127.

[init        ] container is starting...

[cont-env    ] loading container environment variables...

[cont-env    ] APP_NAME: loading...

[cont-env    ] DISPLAY: executing...

[cont-env    ] DISPLAY: terminated successfully.

[cont-env    ] DISPLAY: loading...

[cont-env    ] DOCKER_IMAGE_PLATFORM: loading...

[cont-env    ] DOCKER_IMAGE_VERSION: loading...

[cont-env    ] GTK_THEME: executing...

[cont-env    ] GTK_THEME: /etc/cont-env.d/GTK_THEME: line 6: is-bool-val-true: not found

[cont-env    ] GTK_THEME: terminated successfully.

[cont-env    ] GTK_THEME: loading...

[cont-env    ] HOME: loading...

[cont-env    ] INSTALL_PACKAGES_INTERNAL: executing...

[cont-env    ] INSTALL_PACKAGES_INTERNAL: terminated successfully.

[cont-env    ] INSTALL_PACKAGES_INTERNAL: loading...

[cont-env    ] QT_STYLE_OVERRIDE: executing...

[cont-env    ] QT_STYLE_OVERRIDE: /etc/cont-env.d/QT_STYLE_OVERRIDE: line 6: is-bool-val-true: not found

[cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.

[cont-env    ] QT_STYLE_OVERRIDE: loading...

[cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...

[cont-env    ] XDG_CACHE_HOME: loading...

[cont-env    ] XDG_CONFIG_HOME: loading...

[cont-env    ] XDG_DATA_HOME: loading...

[cont-env    ] XDG_RUNTIME_DIR: loading...

[cont-env    ] container environment variables initialized.

[cont-secrets] loading container secrets...

[cont-secrets] container secrets loaded.

[cont-init   ] executing container initialization scripts...

[cont-init   ] 10-certs.sh: executing...

[cont-init   ] 10-certs.sh: /etc/cont-init.d/10-certs.sh: line 7: is-bool-val-true: not found

[cont-init   ] 10-certs.sh: terminated successfully.

[cont-init   ] 10-check-app-niceness.sh: executing...

[cont-init   ] 10-check-app-niceness.sh: terminated successfully.

[cont-init   ] 10-cjk-font.sh: executing...

[cont-init   ] 10-cjk-font.sh: /etc/cont-init.d/10-cjk-font.sh: line 6: is-bool-val-true: not found

[cont-init   ] 10-cjk-font.sh: terminated successfully.

[cont-init   ] 10-clean-logmonitor-states.sh: executing...

[cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.

[cont-init   ] 10-clean-tmp-dir.sh: executing...

[cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.

[cont-init   ] 10-fontconfig-cache-dir.sh: executing...

[cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.

[cont-init   ] 10-init-users.sh: executing...

[cont-init   ] 10-init-users.sh: /etc/cont-init.d/10-init-users.sh: line 86: sed-patch: not found

[cont-init   ] 10-init-users.sh: terminated with error 127.

[init        ] container is starting...

[cont-env    ] loading container environment variables...

[cont-env    ] APP_NAME: loading...

[cont-env    ] DISPLAY: executing...

[cont-env    ] DISPLAY: terminated successfully.

[cont-env    ] DISPLAY: loading...

[cont-env    ] DOCKER_IMAGE_PLATFORM: loading...

[cont-env    ] DOCKER_IMAGE_VERSION: loading...

[cont-env    ] GTK_THEME: executing...

[cont-env    ] GTK_THEME: /etc/cont-env.d/GTK_THEME: line 6: is-bool-val-true: not found

[cont-env    ] GTK_THEME: terminated successfully.

[cont-env    ] GTK_THEME: loading...

[cont-env    ] HOME: loading...

[cont-env    ] INSTALL_PACKAGES_INTERNAL: executing...

[cont-env    ] INSTALL_PACKAGES_INTERNAL: terminated successfully.

[cont-env    ] INSTALL_PACKAGES_INTERNAL: loading...

[cont-env    ] QT_STYLE_OVERRIDE: executing...

[cont-env    ] QT_STYLE_OVERRIDE: /etc/cont-env.d/QT_STYLE_OVERRIDE: line 6: is-bool-val-true: not found

[cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.

[cont-env    ] QT_STYLE_OVERRIDE: loading...

[cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...

[cont-env    ] XDG_CACHE_HOME: loading...

[cont-env    ] XDG_CONFIG_HOME: loading...

[cont-env    ] XDG_DATA_HOME: loading...

[cont-env    ] XDG_RUNTIME_DIR: loading...

[cont-env    ] container environment variables initialized.

[cont-secrets] loading container secrets...

[cont-secrets] container secrets loaded.

[cont-init   ] executing container initialization scripts...

[cont-init   ] 10-certs.sh: executing...

[cont-init   ] 10-certs.sh: /etc/cont-init.d/10-certs.sh: line 7: is-bool-val-true: not found

[cont-init   ] 10-certs.sh: terminated successfully.

[cont-init   ] 10-check-app-niceness.sh: executing...

[cont-init   ] 10-check-app-niceness.sh: terminated successfully.

[cont-init   ] 10-cjk-font.sh: executing...

[cont-init   ] 10-cjk-font.sh: /etc/cont-init.d/10-cjk-font.sh: line 6: is-bool-val-true: not found

[cont-init   ] 10-cjk-font.sh: terminated successfully.

[cont-init   ] 10-clean-logmonitor-states.sh: executing...

[cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.

[cont-init   ] 10-clean-tmp-dir.sh: executing...

[cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.

[cont-init   ] 10-fontconfig-cache-dir.sh: executing...

[cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.

[cont-init   ] 10-init-users.sh: executing...

[cont-init   ] 10-init-users.sh: /etc/cont-init.d/10-init-users.sh: line 86: sed-patch: not found

[cont-init   ] 10-init-users.sh: terminated with error 127.
`

**Comment by conan7123** [comment]
Having the same issue. Issue started to appear with Version v22.11.2 - rollback to v22.11.1 and its works again.

**Comment by jlesage** [comment]
This is strange, the `docker inspect` doesn't show the correct image version.  Make sure the image and container is properly re-deployed.

You can also try to run this command and see if the container starts correctly:
```
docker pull jlesage/jdownloader-2
docker run --rm jlesage/jdownloader-2
```

**Comment by jlesage** [comment]
Do sure why, but multiple cases have been reported with systems having problems updating the container.  See #125 #127.

**Comment by conan7123** [comment]
Not really useful probably, but manually stoping / removing / pulling / creating the Container **without** using Portainer(-ce) did the trick for me.

Btw. thanks jlesage for your quick reply and also for your work :)

**Comment by RieGo** [comment]
I could also fix it by creating a new (second) container from scratch...

**Comment by jlesage** [comment]
@RieGo, are you also using Portainer ?  Maybe there is an issue with the update mechanism of Portainer ?

**Comment by SanderGit** [comment]
I updated with Ouroboros and also tried with Portainer but both fail. Resetting the container (which supposed to clear the container contents) did not help but the docker pull and run commands work without issue.

**Comment by RieGo** [comment]
one second...
I just found out that I forgot to enter user and group ID in environment vars.
now two problems:
 - it forces me to also fill out "SUP_GROUP_IDS", "INSTALL_PACKAGES" and "VNC_PASSWORD", even though i don't really need those (i think)
 - as soon as i fill those variables, i can't start the container (i.e. "10-init-users.sh: ERROR: group 'grp100' doesn't exists.")
not sure, what sup_group_ids does...

maybe this is the thing that changed, which makes old containers unusable.

and yes, I also use Portainer, usually

**Comment by SanderGit** [comment]
I removed the empty environment variables to no avail. 
grp100 is not a valid Unix group, should just be 100

**Comment by RieGo** [comment]
@SanderGit thanks for the hint! after removing the fields it's working as expected.

**Comment by jlesage** [comment]
> it forces me to also fill out "SUP_GROUP_IDS", "INSTALL_PACKAGES" and "VNC_PASSWORD", even though i don't really need those (i think)

All variables are optional, meaning that they don't have to be defined.  I'm not using Portainer myself, but I guess you can remove the ones that you don't need ?

**Comment by hulleyrob** [comment]
interesting, not had that problem with this app but another container that just would not recreate and pull new image in Portainer in the last few days. Removing the container and recreating it in DSM docker worked for me so maybe that is also the case here.

**Comment by SanderGit** [comment]
Deleting and recreating the container fixed the issue.
