### ISSUE TITLE
change volume

### ISSUE THREAD

**Issue by ph3de** [jlesage/docker-jdownloader-2#132]
hi
how can I change the mapping of download volume?

**Comment by jlesage** [comment]
The mapping is done during the creation of the container.  You can map the `/output` folder of the container to anything on the host with the `-v` parameter of the `docker run` command.

See the quick start as example: https://github.com/jlesage/docker-jdownloader-2#quick-start

**Comment by OneCreek** [comment]
I think about two options for the download directory. 
Meaning I want to mount two volumes: volume1 and volume2 - and therefore get rid of the /output volume...

Like:
cifs-volume1:/output1
cifs-volume2:/output2

Unfortunately than there is always the volume /output being generated because of the dockerfile https://github.com/jlesage/docker-jdownloader-2/blob/d51460a3f58cdda1d29c2fcebc596033c23c8e72/Dockerfile#L77
Is there any chance to adjust this?

Maybe than also a default volume needs to be defined via some env.

**Comment by jlesage** [comment]
You are not required to map `/output`. If you don't want to use it, it is not a problem.

**Comment by OneCreek** [comment]
But than always an unnecessary anonymous volume is created for /output.
I want to prevent that.

I solved it now by mounting the two volume in a default volume ./jDownloader:/output - this way at least no dummy volume is created.
And the two intended volumes to /output/volume1 and /output/volume2.

**Comment by jlesage** [comment]
Closing this issue. Please re-open is needed.
