### ISSUE TITLE
Auto-Extract error on Unraid

### ISSUE THREAD

**Issue by tda90** [jlesage/docker-jdownloader-2#31]
Hello Everyone,
I've installed JDownloader2 on UnRaid but I can't get the auto-extraction to work.
I've also installed the rar,unrar,7zip through the nerd pack but no luck at all.

**Comment by kevincaradant** [comment]
Hi
I'm not sure why but since today, I can't anymore use autoextract on my NUC with ubuntu 64 bits.
I change some settings today on the output path, it was broken after that, so I write again as before, and it's still broken, so is it a coincidence or a really bug ? 
I get this display:
![image](https://user-images.githubusercontent.com/6093175/57975552-72a13400-79cb-11e9-86b3-da82a78557bc.png)
Maybe it's not only on your UnRaid device that we have this issue ?
