### ISSUE TITLE
Can dockerized JDownloader and FileBot applications communicate with the event scripter? 

### ISSUE THREAD

**Issue by mtoensing** [jlesage/docker-jdownloader-2#38]
Hi,

since @jlesage maintains the filebot and jdownloader docker images maybe someone know how to start the Filebot after a download has finished in the jdownloader image. If both applications would run in a single image or on a local machine I could use the event scripter. But how does this work with docker?

**Comment by jlesage** [comment]
Now that FileBot has a watch folder, you could copy/move the finished downloads to FileBot's watch folder.  Is it something possible?

**Comment by mtoensing** [comment]
Ok great. And why not use the download folder for the watch folder? But the problem remains: how do I trigger the copy script if the download folder does not work?

**Comment by jlesage** [comment]
Using the same folder for downloads and watch folder could cause issue where FileBot starts renaming stuff before download completes (for example, if a download stalls for too long).

What you can do is, for example,  the following volume mappings:

| Host folder | JD container folder | FileBot container folder|
| ------------|--------------------|------------------------|
/home/user/downloads | /output | |
/home/user/filebot_watch | /filebot_watch | /watch |
/home/user/media | | /output

Then, in JD container, you copy/move finished download to `/filebot_watch/`.  Since this folder is also mapped to the FileBot container, FileBot will automatically rename files and put them in its `/output` folder.

Hopes this make sense...

**Comment by mtoensing** [comment]
Thanks for your answer. But how to I copy files in another folder if they finished downloading/unpacking? What is the trigger?

**Comment by jlesage** [comment]
Yeah it seems that there is no obvious way to move downloaded files to another directory...  However, if you download archives, you can change the destination of extracted files (under the `Archive Extractor` settings).  You could set this setting to the FileBot's watch folder.

**Comment by mtoensing** [comment]
Works. Thank you.
